from __future__ import annotations

import json
import math

from .config import MODEL_DIR
from .engine_model import EngineInputs, ReducedOrderPistonEngine


PARAMS = [
    "Engine_RPM",
    "EGT1",
    "EGT2",
    "EGT3",
    "CHT",
    "Fuel_Flow",
    "Oil_Temp",
    "Oil_Pressure",
    "Battery_Voltage",
    "Battery_Current",
    "Alternator_Temp",
    "EFI_Fuel_Temp",
    "EFI_Water_Temp",
    "MAP_Injector",
]


ENGINE_MODEL_MAP = {
    "Engine_RPM": "Engine_RPM",
    "EGT1": "EGT1",
    "EGT2": "EGT2",
    "EGT3": "EGT3",
    "CHT": "CHT",
    "Fuel_Flow": "Fuel_Flow",
    "Oil_Temp": "Oil_Temp",
    "Oil_Pressure": "Oil_Pressure",
    "Battery_Voltage": "Battery_Voltage",
    "Battery_Current": "Battery_Current",
    "Alternator_Temp": "Alternator_Temp",
    "EFI_Fuel_Temp": "EFI_Fuel_Temp",
    "EFI_Water_Temp": "EFI_Water_Temp",
    "MAP_Injector": "MAP_Injector",
}


class ReferenceTwin:
    """
    Mission-aware healthy Digital Twin.

    Two operating modes are supported:

    1. ACES / real telemetry:
       Statistical healthy-reference data is combined with
       the reduced-order physics model.

    2. UAV simulation:
       The reduced-order engine model is used as the primary
       healthy reference because the simulated telemetry is
       generated by that same model.

    This prevents the simulator from generating artificial
    faults simply because two different healthy-reference
    domains use different absolute sensor distributions.
    """

    def __init__(self):
        self.stats = json.loads(
            (MODEL_DIR / "healthy_reference.json").read_text(
                encoding="utf-8"
            )
        )

        self.engine_model = ReducedOrderPistonEngine()

    @property
    def operating_states(self) -> list[str]:
        return sorted(
            key
            for key in self.stats
            if key != "_GLOBAL_"
        )

    def expected(
        self,
        operating_state: str,
    ) -> dict:
        state = self.stats.get(
            str(operating_state),
            self.stats["_GLOBAL_"],
        )

        return {
            key: value["median"]
            for key, value in state.items()
        }

    def _contextual_expected(
        self,
        ref: dict,
        context: dict | None,
    ) -> dict:

        expected = {
            parameter: float(
                ref[parameter]["median"]
            )
            for parameter in PARAMS
        }

        if not context:
            return expected

        altitude_factor = (
            max(
                0.0,
                float(
                    context.get(
                        "altitude_ft",
                        3000,
                    )
                ),
            )
            / 10000.0
        )

        hot_factor = (
            max(
                0.0,
                float(
                    context.get(
                        "ambient_c",
                        25,
                    )
                )
                - 25.0,
            )
            / 25.0
        )

        endurance_factor = (
            max(
                0.0,
                float(
                    context.get(
                        "duration_h",
                        4,
                    )
                )
                - 4.0,
            )
            / 8.0
        )

        expected["MAP_Injector"] *= (
            1.0
            + 0.08 * altitude_factor
        )

        for key in [
            "EGT1",
            "EGT2",
            "EGT3",
        ]:
            expected[key] *= (
                1.0
                + 0.025 * altitude_factor
                + 0.035 * hot_factor
                + 0.020 * endurance_factor
            )

        expected["Oil_Temp"] *= (
            1.0
            + 0.020 * hot_factor
            + 0.020 * endurance_factor
        )

        expected["EFI_Water_Temp"] *= (
            1.0
            + 0.025 * hot_factor
            + 0.015 * endurance_factor
        )

        expected["CHT"] *= (
            1.0
            + 0.020 * altitude_factor
            + 0.040 * hot_factor
            + 0.020 * endurance_factor
        )

        expected["Alternator_Temp"] *= (
            1.0
            + 0.015 * hot_factor
            + 0.010 * endurance_factor
        )

        if bool(
            context.get(
                "rapid_throttle",
                False,
            )
        ):
            expected["Engine_RPM"] *= 1.04
            expected["Fuel_Flow"] *= 1.08

        return expected

    def _physics_expected(
        self,
        ref: dict,
        context: dict | None,
    ) -> dict:

        """
        Generate physics-informed expected values.

        The engine model is first evaluated at the current
        mission operating point and at its nominal reference
        operating point.

        Relative changes are then applied to the ACES
        measurement-domain medians.

        For UAV simulation mode, the direct physics prediction
        is returned because the observed telemetry itself is
        generated from the same engine model.
        """

        context = context or {}

        rpm = float(
            context.get(
                "rpm",
                context.get(
                    "Engine_RPM",
                    3000.0,
                ),
            )
        )

        throttle = float(
            context.get(
                "throttle",
                0.60,
            )
        )

        altitude = float(
            context.get(
                "altitude_ft",
                3000.0,
            )
        )

        ambient = float(
            context.get(
                "ambient_c",
                25.0,
            )
        )

        load = context.get(
            "load"
        )

        current = self.engine_model.predict(
            EngineInputs(
                rpm=rpm,
                throttle=throttle,
                altitude_ft=altitude,
                ambient_c=ambient,
                load=load,
            )
        )

        reference = self.engine_model.predict(
            EngineInputs(
                rpm=3000.0,
                throttle=0.60,
                altitude_ft=3000.0,
                ambient_c=25.0,
                load=None,
            )
        )

        physics_expected = {}

        for parameter in PARAMS:

            model_key = ENGINE_MODEL_MAP[
                parameter
            ]

            ref_model = max(
                abs(
                    float(
                        reference[
                            model_key
                        ]
                    )
                ),
                1e-9,
            )

            ratio = (
                float(
                    current[
                        model_key
                    ]
                )
                / ref_model
            )

            physics_expected[
                parameter
            ] = (
                float(
                    ref[
                        parameter
                    ]["median"]
                )
                * ratio
            )

        return physics_expected

    def _direct_simulation_expected(
        self,
        context: dict,
    ) -> dict:

        """
        Generate the exact healthy reference for the
        simulated UAV engine.

        This is intentionally based on the same reduced-order
        engine model that generated the simulated telemetry.

        Therefore:

            healthy simulator
                    ↓
            engine model
                    ↓
            expected simulator telemetry

        should produce near-zero residuals.
        """

        rpm = float(
            context.get(
                "rpm",
                context.get(
                    "Engine_RPM",
                    3000.0,
                ),
            )
        )

        throttle = float(
            context.get(
                "throttle",
                0.60,
            )
        )

        altitude = float(
            context.get(
                "altitude_ft",
                3000.0,
            )
        )

        ambient = float(
            context.get(
                "ambient_c",
                25.0,
            )
        )

        load = context.get(
            "load"
        )

        model = self.engine_model.predict(
            EngineInputs(
                rpm=rpm,
                throttle=throttle,
                altitude_ft=altitude,
                ambient_c=ambient,
                load=load,
            )
        )

        return {
            parameter: float(
                model[
                    ENGINE_MODEL_MAP[
                        parameter
                    ]
                ]
            )
            for parameter in PARAMS
        }

    def compare(
        self,
        telemetry: dict,
        context: dict | None = None,
    ):

        context = context or {}

        state = str(
            telemetry.get(
                "Operating_State",
                "_GLOBAL_",
            )
        )

        ref = self.stats.get(
            state,
            self.stats["_GLOBAL_"],
        )

        simulation_mode = str(
            context.get(
                "data_source",
                "",
            )
        ).lower() in {
            "simulation",
            "uav_simulation",
            "live_uav",
        }

        if simulation_mode:

            expected = (
                self._direct_simulation_expected(
                    context
                )
            )

            physics_expected = dict(
                expected
            )

        else:

            contextual_expected = (
                self._contextual_expected(
                    ref,
                    context,
                )
            )

            physics_expected = (
                self._physics_expected(
                    ref,
                    context,
                )
            )

            expected = {
                parameter: (
                    0.70
                    * float(
                        contextual_expected[
                            parameter
                        ]
                    )
                    + 0.30
                    * float(
                        physics_expected[
                            parameter
                        ]
                    )
                )
                for parameter in PARAMS
            }

        residuals = {}
        z_scores = {}
        percentage_deviation = {}

        for parameter in PARAMS:

            observed = float(
                telemetry[
                    parameter
                ]
            )

            median = float(
                expected[
                    parameter
                ]
            )

            if simulation_mode:

                # Simulation telemetry and expected values
                # are generated from the same engine model.
                #
                # Use a small engineering tolerance instead
                # of ACES statistical variance because the
                # simulation has deterministic model output.

                reference_value = max(
                    abs(median),
                    1e-6,
                )

                std = max(
                    reference_value
                    * 0.03,
                    1e-6,
                )

            else:

                std = max(
                    float(
                        ref[
                            parameter
                        ]["std"]
                    ),
                    1e-6,
                )

            residual = (
                observed
                - median
            )

            residuals[
                parameter
            ] = residual

            z_scores[
                parameter
            ] = (
                residual
                / std
            )

            percentage_deviation[
                parameter
            ] = (
                100.0
                * residual
                / abs(median)
                if abs(median) > 1e-9
                else 0.0
            )

        max_abs_z = max(
            abs(value)
            for value in z_scores.values()
        )

        residual_rms = math.sqrt(
            sum(
                value * value
                for value in z_scores.values()
            )
            / len(z_scores)
        )

        dominant = sorted(
            (
                {
                    "parameter": parameter,
                    "z_score": round(
                        float(
                            z_scores[
                                parameter
                            ]
                        ),
                        3,
                    ),
                    "residual": round(
                        float(
                            residuals[
                                parameter
                            ]
                        ),
                        3,
                    ),
                    "percentage_deviation": round(
                        float(
                            percentage_deviation[
                                parameter
                            ]
                        ),
                        2,
                    ),
                }
                for parameter in PARAMS
            ),
            key=lambda item: abs(
                item["z_score"]
            ),
            reverse=True,
        )[:5]

        return {
            "operating_state": state,
            "expected": expected,
            "physics_expected": physics_expected,
            "residuals": residuals,
            "z_scores": z_scores,
            "percentage_deviation": percentage_deviation,
            "residual_rms": residual_rms,
            "max_abs_z": max_abs_z,
            "dominant_deviations": dominant,
            "reference_alarm": (
                max_abs_z >= 3.0
            ),
            "simulation_mode": simulation_mode,
            "reference_note": (
                "UAV simulation uses a physics-consistent "
                "healthy reference generated by the same "
                "reduced-order engine model as the simulated "
                "telemetry. ACES/real telemetry uses the "
                "hybrid statistical + physics reference."
                if simulation_mode
                else
                "Hybrid healthy-reference Twin: ACES "
                "operating-state statistics blended with "
                "a calibrated reduced-order engine model "
                "for mission-context response."
            ),
        }
